repos:
-   repo: https://github.com/pycqa/isort
    language: python
    rev: 5.3.2
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/python/black
    language: python
    rev: 19.10b0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://gitlab.com/pycqa/flake8
    language: python
    rev: 3.8.3
    hooks:
    - id: flake8
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: __init__.py
