"""Create list of files with unexpected properties (bright spots, or over all too dark)

Usage:
find_images_with_artefacts.py [-h] [-f] brightness_file {find_too_bright,find_too_dark} threshold [output]

Create list of files with unexpected properties, i.e. with very bright spots, or images
that are overall too dark, based on the brightness file that was generated by 
compute_mean_and_max_brightness.py.
This is to identify photos where e.g. a fish was very close to the camera, creating a
very bright spot.
Or images in a dataset where the timing of the strobe trigger was off, and there are
some images that are very dark, because the strobes did not fire.
Both these types of images should be excluded for the training of image attenuation
parameters with correct_images, for classification with georef_semantics, as well as for
texture map generation with texture_mapping.

positional arguments:
  brightness_file       File with max brightness values, generated by
                        compute_mean_and_max_brightness.py
  {find_too_bright,find_too_dark}
                        Whether to find very bright or very dark images.
                        If 'find_too_bright', images with a max_brightness larger than 
                        the threshold are selected. If 'find_too_dark', images
                        with mean_brightness smaller than the threshold are returned.
  threshold             Threshold for brightness
  output                File with list of images with max brightness larger than
                        threshold (default: filelist_images_with_potential_outliers.txt)

optional arguments:
  -h, --help            show this help message and exit
  -f, --force           Overwrite existing output file (default: False)

Copyright (c) 2024-2026, University of Southampton
All rights reserved.
Licensed under the BSD 3-Clause License.
See LICENSE.md file in the project root for full license information.
"""

import argparse
from pathlib import Path
import pandas as pd

parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    description=(
        "Create list of files with unexpected properties, i.e. with very bright spots, "
        "or images that are overall too dark, based on the brightness file that was "
        "generated by compute_mean_and_max_brightness.py."
        "This is to identify photos where e.g. a fish was very close to the camera, "
        "creating a very bright spot."
        "Or images in a dataset where the timing of the strobe trigger was off, and "
        "there are some images that are very dark, because the strobes did not fire."
        "Both these types of images should be excluded for the training of image "
        "attenuation parameters with correct_images, for classification with "
        "georef_semantics, as well as for texture map generation with texture_mapping."
    ),
)
parser.add_argument(
    "brightness_file",
    help=(
        "File with max brightness values, generated by "
        "compute_mean_and_max_brightness.py"
    )
)
parser.add_argument(
    "mode",
    type=str,
    choices=["find_too_bright", "find_too_dark"],
    help=(
        "Whether to find very bright or very dark images. If 'find_too_bright', images "
        "with a max_brightness larger than the threshold are selected. "
        "If 'find_too_dark', images with mean_brightness smaller than the threshold "
        "are returned."
    )
)
parser.add_argument(
    "threshold", type=int, help="Threshold for brightness"
)
parser.add_argument(
    "output",
    type=str,
    nargs="?",
    default="filelist_images_with_potential_outliers.txt",
    help="File with list of images with max brightness larger than threshold",
)
parser.add_argument(
    "-f", "--force", action="store_true", help="Overwrite existing output file"
)
args = parser.parse_args()

if (Path(args.output).exists()) and (not args.force):
    print(f"Output file {args.output} already exists. Use --force to overwrite.")
    exit(1)

df = pd.read_csv(args.brightness_file)

if args.mode == "find_too_bright":
    bad_ones = df[df["max_brightness"] > args.threshold]
elif args.mode == "find_too_dark":
    bad_ones = df[df["mean_brightness"] < args.threshold]
else:
    raise ValueError(f"Unknown mode: {args.mode}")

number_above_threshold = len(bad_ones)
print(
    "Number of images with "
    f"{'max_brightness larger' if args.mode == 'find_too_bright' else 'mean_brightness smaller'} "
    f"than {args.threshold}: {number_above_threshold}"
)
bad_ones.to_csv(args.output, columns=["path"], index=False, header=False)
print("If you want to copy the images to a folder, use this command:")
print("mkdir FOLDER_TO_COPY_TO")
print("cat", args.output, "| xargs -I {} cp {} FOLDER_TO_COPY_TO/")
print(
    "Once you have a filelist of images with artefacts, you can generate a filelist of "
    "images without artefacts using this command:"
    "grep -v -f outlier_images.txt full_file_list.txt > file_list_without_outliers.txt"
)
print(
    "Or, in case you want to delete the identified images (e.g. remove the too dark "
    "images) it is savest to move them first to a different folder, e.g using this "
    "command:"
)
print("mkdir FOLDER_TO_MOVE_TO")
print("cat", args.output, "| xargs -I {} mv {} FOLDER_TO_MOVE_TO/")
print(
    "Once you are happy that the images have been moved correctly, you can delete "
    "the folder with the moved images."
)
